name: inject.example.train
description: A more complex example of using package:inject

dependencies:
  inject:
    path: ../../package/inject

dev_dependencies:
  build_runner: ^1.10.3
  build_test: ^1.2.2
  build_web_compilers: ^2.12.1
  inject_generator:
    path: ../../package/inject_generator
  test: ^1.15.4
